$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        350:{
            items:2
        },
        700:{
            items:5
        },
        1000:{
            items:8
        }
    }
})